name: Deploy to Fly.io

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mise
        uses: jdx/mise-action@v2
        
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy
        run: mise run build-deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
